# Generated by Django 3.0.2 on 2020-01-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='user',
            new_name='usuario',
        ),
    ]
