# Generated by Django 3.0.2 on 2020-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_auto_20200131_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=7.77, max_digits=3),
        ),
    ]
