# Generated by Django 3.0.2 on 2020-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recursos'),
        ),
    ]
